### PR TITLE
fix link to JsonColumnTest.scala in README.md

### PR DESCRIPTION
**Pull request by skrauchenia**

### CODE REVIEW

**Comment by skrauchenia** [comment]
It seems that build is broken

```
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Unavailable url=http://maven.websudos.co.uk/ext-release-local/com/datastax/cassandra/cassandra-driver-parent/2.1.5/cassandra-driver-parent-2.1.5.jar
[error] SERVER ERROR: Service Unavailable url=http://maven.websudos.co.uk/ext-snapshot-local/com/datastax/cassandra/cassandra-driver-parent/2.1.5/cassandra-driver-parent-2.1.5.jar
[info] Resolving com.websudos#util-testing_2.11;0.6.12 ...
[error] SERVER ERROR: Service Unavailable url=http://maven.websudos.co.uk/ext-release-local/com/websudos/util-testing_2.11/0.6.12/util-testing_2.11-0.6.12.pom
[error] SERVER ERROR: Service Unavailable url=http://maven.websudos.co.uk/ext-snapshot-local/com/websudos/util-testing_2.11/0.6.12/util-testing_2.11-0.6.12.pom
```

I found an old issue which most likely describes this problem

**Comment by alexflav23** [comment]
@skrauchenia On it now, seems a dependency has gone missing.

**Comment by alexflav23** [comment]
Just released the dependency in question to Maven Central to prevent any further issues because of it. We are currently in the process of moving a large part of out infrastructure between cloud providers, so maven servers may well have issues until the process is complete.

**Comment by skrauchenia** [comment]
That's great! Thanks!

**Comment by skrauchenia** [comment]
Is it possible to rerun this build since issue with dependencies had been resolved?

**Comment by alexflav23** [comment]
@skrauchenia A new version of the util library currently causing this issue is about to hit Maven Central. As soon as that happens we will release the phantom fixes from the internal source control to GitHub and fix the Travis build as well.

**Comment by alexflav23** [comment]
Hi @skrauchenia  , we've moved all documentation to Github Wiki and fixed all broken links in the process. I will now close this PR as it's out of date.

**Pull request closed without merging**
