### PR TITLE
(#260) Adding OptionalTimeUUIDColumn

### PR DESCRIPTION
**Pull request by mmatloka**

### CODE REVIEW

**Comment by mmatloka** [comment]
Travis `No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.` interesting.

**Comment by alexflav23** [comment]
Hi @mmatloka,

I've manually restarted the build in hope it passes this time. Travis is very unreliable but nonetheless free.

Regards.

**Comment by mmatloka** [comment]
Build passed ;)

**Comment by mmatloka** [comment]
In what release this will be included? :) (its not in `1.9.3`)

**Comment by alexflav23** [comment]
@mmatloka I was under the impression this would be available in the new release. I will double check what happened, sounds like merge gone wrong. You should have this live shortly.

**Comment by mmatloka** [comment]
Seems to be fixed in `1.9.5`

**Pull request merged**
