### PR TITLE
SmallInt and TinyInt support

### PR DESCRIPTION
**Pull request by mmatloka**

### CODE REVIEW

**Comment by alexflav23** [comment]
Hi @mmatloka,

This is a known Travis CI pain point, their version of Cassandra is pretty old. We have a mechanism that allows use to write tests based on the version of Cassandra being used and we are deploying a fully embedded solution with 3.0.0 shortly.

Regards.

**Comment by mmatloka** [comment]
Branch corrected, working under travis. If merged, than I'll correct the local date related one.

**Comment by mmatloka** [comment]
hey @alexflav23 when version containing this feature can be released? :) it's very valuable for one of my projects.

**Comment by alexflav23** [comment]
@mmatloka ,

`1.21.5` out now, in cinemas everywhere! :)

Regards.

**Comment by mmatloka** [comment]
Thanks! :)

**Pull request merged**
