### PR TITLE
When determining whether Cassandra is already running, test port availability on all internet addresses for localhost and do not grep the process list for cassandra. Resolves #163.

### LINKED ISSUE #163: CassandraStateManager.cassandraRunning returns false positive in some cases
Because process looks like this:
```
bin/../resources/cassandra/bin/cqlsh
```
and `cassandraRunning` method only checks if cassandra is present in `ps` output.

### PR DESCRIPTION
**Pull request by brenttheisen**
I suspect the reason the `ps -ef | grep cassandra` thing was added to the codebase is because the `isPortAvailable` method was not always returning `true` when Cassandra was actually listening on whatever port was passed to it. This is most likely because the cassandra.yaml used by the embedded Cassandra server does not bind to 0.0.0.0 whereas that is exactly what the `new ServerSocket(port)` does by default. I was able to reproduce this...

```
brent@wasted:~$ telnet localhost 9142
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]
telnet> c
Connection closed.
brent@wasted:~$ scala
Welcome to Scala version 2.11.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import java.net.{ServerSocket, InetAddress}
import java.net.{ServerSocket, InetAddress}

scala> val ss = new ServerSocket(9142) // We were counting on this throwing a exception
ss: java.net.ServerSocket = ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9142]

scala> ss.close()

scala> val inetAddrs = InetAddress.getAllByName("localhost")
inetAddrs: Array[java.net.InetAddress] = Array(localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1)

scala> inetAddrs.foreach(inetAddr => new ServerSocket(9142, 1, inetAddr).close())
java.net.BindException: Address already in use
  at java.net.PlainSocketImpl.socketBind(Native Method)
  at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
  at java.net.ServerSocket.bind(ServerSocket.java:376)
  at java.net.ServerSocket.<init>(ServerSocket.java:237)
  at $anonfun$1.apply(<console>:10)
  at $anonfun$1.apply(<console>:10)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  ... 33 elided
```

Similar to the last statement above, this PR changes `isPortAvailable` so it attempts to instantiate a new `ServerSocket` on every `InetAddress` associated with `localhost`.

### CODE REVIEW

**Comment by alexflav23** [comment]
@brenttheisen Many thanks for this, I've been looking at it over and over again. We will test more thoroughly but it seems this might work. We also use an approach where we directly attempt to connect to Cassandra, avoiding all the port fun, at least from our end.

**Comment by brenttheisen** [comment]
No problem @alexflav23.

**Comment by alexflav23** [comment]
Hi @brenttheisen,

Many thanks for your contribution once again. I've manually merged the fix into the next release branch and it should be in the wild very shortly. Apologies for the delay in integrating this, phantom has been undergoing major re-works.

We are now also attempting to connect to Cassandra to determine run status, it's much safer and it seems to work reliably and quite nicely in practice. SBT even gracefully shuts the Embedded Cassandra down on exit and all the things you'd expect.

Regards.

**Comment by brenttheisen** [comment]
Thanks @alexflav23.

**Pull request closed without merging**
