### PR TITLE
Query result can be handled as Scala iterator

### PR DESCRIPTION
**Pull request by mmatloka**

### CODE REVIEW

**Comment by alexflav23** [comment]
HI @mmatloka,

So we start this with the assumption that the newly added method is not good for large result sets, therefore somewhat defying the purpose of the iterator. We also have a potentially very expensive conversion as you probably have an `O(n)` traversal in the `asScala` conversion, which makes me wonder why bother with this at all.

We have Iteratees, Streams and what have you, and we also have lists for smaller result sets. Is there any particular circumstance where this would clearly outperform a trivial `List`?

Regards,
Flavian

**Comment by mmatloka** [comment]
`asScala` in this case just creates a wrapper (`JIteratorWrapper`) around `ResultSet` (java) iterator without evaluating it. And the `ResultSet.iterator()` is valid for big results as it does not fetch full content at once (its even mentioned in javadocs). So this combination also should be valid for big datasets, without using of any play or twitter classes.

**Comment by mmatloka** [comment]
@alexflav23 ^ ? :)

**Comment by alexflav23** [comment]
Hi @mmatloka ,

Happy to merge this but I don't really understand what kind of back pressure this approach offers, forgive me if I am wrong. The `BigTest` implementations have dropped in size a lot and we are only sampling 100 records. Usually we would do 1m or 10m insertions + iterations on a local cluster and monitor memory pressure across the board before we deem everything a success.

Do you think we can work together to come up with a more ample testing approach before merging this? Otherwise it's all looking good, it's just one of those seemingly simple things which may wind up bitting you later on, I imagine a lot of people will like the new `iterator` method mainly due to its simplicity.

Regards,
Flavian

**Comment by mmatloka** [comment]
Hi @alexflav23,
Sure, we can make more tests for this. However I started to wonder if it wouldn't be better to alter a bit this implementation, since theoretically optimal `ResultSet ` iteration performs some prefetching like in: https://datastax.github.io/java-driver/features/paging/#result-set-iteration

```
ResultSet rs = session.execute("your query");
for (Row row : rs) {
    if (rs.getAvailableWithoutFetching() == 100 && !rs.isFullyFetched())
        rs.fetchMoreResults(); // this is asynchronous
    // Process the row ...
}
```

Wrapping in scala iterator performs just an equivalent of:
```
ResultSet rs = session.execute("your query");
for (Row row : rs) {
  // Process the row ...
}
```

**Comment by alexflav23** [comment]
Hi @mmatloka,

Which is exactly what we already do via 2 existing DSLs, such as play iterators and Twitter Spools and I was a bit weary about adding yet another option with no noticeable improvement to the former.

Do you think having this will make a big difference?

Regards,
Flavian

**Pull request merged**
