### PR TITLE
LocalDateColumn

### PR DESCRIPTION
**Pull request by mmatloka**

### CODE REVIEW

**Comment by alexflav23** [comment]
Hi @mmatloka ,

What version of Cassandra does this require? Travis CI is a bit behind schedule on that and you would need to use the per version testing method.
```if (session.v3OrNewer) {
 // do this
}```

Another way is to use ```scala
if (cassandraVersion > Versions.`2.2.0`) {
  "test should succeed"
} else {
  "the feature should not be enabled.
}
```


Regards.

**Comment by mmatloka** [comment]
> What version of Cassandra does this require?
2.2.0

i'll correct this soon.

**Comment by mmatloka** [comment]
In both this and https://github.com/websudos/phantom/pull/413 there is a problem with writing tests with per version testing method, just because I've added those new columns to Primitives and Joda Primitives objects used during tests, and they are used also for more complex scenarios like batch testing, and disabling them for <2.2.0 would also mean disabling batch tests for <2.2.0...

**Comment by mmatloka** [comment]
Concerning my cassandra tries - according to docs and some issues around travis ci github, this should work, but in practice it does not ;)

**Comment by alexflav23** [comment]
Hi @mmatloka ,

The build is completely broken, it's not failing for just these couple of tests. Based on your last commit, it isn't even starting because of a permission error, you're not allowed to use `sudo` in Travis. Not sure if this is in your changeset or if it's just going crazy.

**Comment by mmatloka** [comment]
Yeah, I know, I was trying alternative way of setting up cassandra for travis and looks like it does not work (or cannot be connected to). So the whole build is broken because tests cant connect to cassandra. It is possible to use sudu in some scenarios, but according to some "people" and some repos on github using travis, it should just work, even without sudo, but it does not ;)

I'll later clean my branch, so that it does not contains all my experiments related to travis.

**Comment by mmatloka** [comment]
@alexflav23 what do you think regarding https://github.com/websudos/phantom/pull/418#issuecomment-181596709 ?

**Comment by alexflav23** [comment]
Hi @mmatloka,

The fix is a bit different, you would need to isolate the new columns in different tables obviously so you can individually target new behaviour. It's generally a bad idea to alter existing test domain structures instead of isolating new ones just because there's a relatively high risk of unwanted coupling. Case and point here.

With the right level of separation, we can have all the needed on and off toggling. We are also working on upgrading the embedded plugin to support the newest Cassandra which will help eliminate the need for using the native Travis one.

Regards.

**Comment by mmatloka** [comment]
not yet fully working, need to add codec

**Comment by mmatloka** [comment]
Added codec, but it needed `cassandra-driver-extras`

**Comment by alexflav23** [comment]
Hi @mmatloka,

I don't really see why that's needed, we already had an `JodaTime` column that worked out nicely with everything, perhaps you could help me pin point it and I'll play around with it myself.

Anyhow, we are missing a type alias inside `package.scala`. You don't really need a new column for this, you can just add a new type alias to the default list. Have a look [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/dsl/package.scala#L78).

Regards.

**Comment by mmatloka** [comment]
I don't see the code now, but what I remember there was a 'DateTimeColumn',
which refers to cql 'timestamp' type. But with Cassandra 2.2 there is also
a cql 'date' and phantom does not have a column for it?

**Comment by alexflav23** [comment]
Hi @mmatloka,

What I truly meant and apologies for not being clear, is that we where able to implement Joda columns by simply implementing the primitive. How come the mechanism of implementing this column is so different?

I'm not arguing it either way, just looking to understand where the discrepancy comes from.

Regards.

**Comment by mmatloka** [comment]
> What I truly meant and apologies for not being clear, is that we where able to implement Joda columns by simply implementing the primitive. How come the mechanism of implementing this column is so different?

Hmm, I have followed the cases of `DateColumn` and `DateTimeColumn` which are not defied just as aliases byt also as sepearate column classes, without thinking why they are implemented this way?

**Comment by alexflav23** [comment]
In the case of other columns the reason was type restrictions and refinements in ordering and so on, probably obsolete right now.

Anyway, what I was referring to is needing a new `MappingCodec` and the `extras` dependency, I didn't quite follow on what that brings in, is it a parsing issue or does that do specifically?

Regards.

**Comment by mmatloka** [comment]
Without `Codec` the `serialize a cassandra 2.2 primitives insert query` falls with `Codec not found for requested operation: [date <-> org.joda.time.LocalDate]`.This codec can be also used by more advances cases like collection type columns using `date`.

**Pull request merged**
